ci: code-quality: tree: disable job
The following error is shown:
Running sah-analysis with runner ScanTree
src/dmdeviceadapter/amx/adapter/DM_AmxReset.h:0:0: error: Illegal file 'DM_AmxReset.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/adapter/DM_AmxAddDelete.h:0:0: error: Illegal file 'DM_AmxAddDelete.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/adapter/DM_AmxSystemConnection.h:0:0: error: Illegal file 'DM_AmxSystemConnection.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/adapter/DM_DeviceAdapter.h:0:0: error: Illegal file 'DM_DeviceAdapter.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/adapter/DM_AmxParameterValues.h:0:0: error: Illegal file 'DM_AmxParameterValues.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/adapter/DM_AmxUpDownload.h:0:0: error: Illegal file 'DM_AmxUpDownload.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/adapter/DM_AmxACSConnection.h:0:0: error: Illegal file 'DM_AmxACSConnection.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/adapter/DM_AmxParameterNames.h:0:0: error: Illegal file 'DM_AmxParameterNames.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/adapter/DM_AmxChangeDUState.h:0:0: error: Illegal file 'DM_AmxChangeDUState.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/adapter/DM_AmxCommon.h:0:0: error: Illegal file 'DM_AmxCommon.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/adapter/DM_AmxRPCInterface.h:0:0: error: Illegal file 'DM_AmxRPCInterface.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/adapter/DM_AmxScheduleDownload.h:0:0: error: Illegal file 'DM_AmxScheduleDownload.h' in source directory adapter
Only allowed files are "['.md', 'Makefile', 'makefile', '.mk', '.c', '.y', '.l', '.lua', '.py', '.version']"
src/dmdeviceadapter/amx/cwmp_plugin/odl: error: Illegal directory odl
src/dmdeviceadapter/amx/cwmp_plugin/scripts: error: Illegal directory scripts

This repository structure has always been in place for the tr069-manager, so let's disable the check for now so that we can keep the other parts of the CI.

Signed-off-by: Matthias Franck <matthias.franck@softathome.com>